config/routes.rb
CodePaste::Application.routes.draw do

  resources :pastes

  root :to => 'pastes#new'

  

end

app/models/parser.rb
class Parser < ActiveRecord::Base
  has_many :pastes

  validates_uniqueness_of :name
  validates_uniqueness_of :display_name
  validates_presence_of :name
  validates_presence_of :display_name

  def self.lang_counts
    lang_cnt = {}
    Parser.includes(:pastes).each do |parser|
      lang_cnt[parser.display_name] = parser.pastes.size
    end

    lang_cnt
  end
end

app/models/paste.rb
class Paste < ActiveRecord::Base
  belongs_to :parser

  before_validation :calc_num_of_lines

  validates_presence_of :code
  validates_presence_of :number_of_lines
  validates_numericality_of :number_of_lines, :only_integer => true, :greater_than => 0

  validates_presence_of :parser

  # scope :within_last_day, where('created_at >= ?', 1.days.ago)
  # scope :within_last_week, where('created_at >= ?', 7.days.ago)
  # scope :this_month, where('created_at >= ? and created_at <= ?', Time.now.beginning_of_month, Time.now.end_of_month)
  # scope :last_month, where('created_at >= ? and created_at <= ?', 1.months.ago.beginning_of_month, 1.months.ago.end_of_month)
  # scope :this_year, where('created_at >= ? and created_at <= ?', Time.now.beginning_of_year, Time.now.end_of_year)

  def code_summary(lines_to_capture)
    lines = self.code.split("\r\n")[0..lines_to_capture]

    lines.size > 1 ? code_snip = lines.join("\r\n") : code_snip = lines.first
  end

  def line_numbers
    doc = get_parsed_code

    lin_num = ''

    doc.xpath('//pre').each do |root|
      root.children.each do |n|
        if n['class'] == 'line-numbers'
          lin_num << n.content.strip + "\n"
        end
      end
    end

    lin_num
  end

  def highlighted_code
    doc = get_parsed_code

    hcode = ""

    doc.xpath('//pre').each do |root|
      if root['class'] == 'twilight'
        root['id'] = 'source-code'
      end

      root.children.each do |n|
        if n['class'] == 'line-numbers'
          n.unlink
        end
      end
    end

    doc
  end

  private
  def get_parsed_code
    parsed_output = Uv.parse(self.code, 'xhtml', self.parser.name, true, 'blackboard')
    doc = Nokogiri::HTML(parsed_output)
  end

  def calc_num_of_lines
    return if self.code.blank? || self.parser.blank?

    doc = get_parsed_code

    lin_num = ''

    doc.xpath('//pre').each do |root|
      root.children.each do |n|
        if n['class'] == 'line-numbers'
          lin_num = ''
          lin_num << n.content.strip
        end
      end
    end

    self.number_of_lines = lin_num.to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
  # GET /pastes
  # GET /pastes.xml
  def index
    @pastes = Paste.paginate :page => params[:page], :order => 'updated_at DESC', :per_page => 10

    @all_pastes_count = Paste.all.length
    @lang_counts = Parser.lang_counts
    @day_count = Paste.within_last_day.count
    @week_count = Paste.within_last_week.count
    @this_month_count = Paste.this_month.count
    @last_month_count = Paste.last_month.count
    @this_year = Paste.this_year.count

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /pastes/1
  # GET /pastes/1.xml
  def show
    @paste = Paste.find_by_id(params[:id])

    respond_to do |format|
      if @paste
        format.html # show.html.erb
        format.text { render :text => @paste.code }
      else
        format.html { response_to_missing_id }
        format.text { response_to_missing_id }
      end
    end
  end

  # GET /pastes/new
  # GET /pastes/new.xml
  def new
    @paste = Paste.new
    @parsers = Parser.order('display_name desc')

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /pastes/1/edit
  def edit
    @paste = Paste.find_by_id(params[:id])
    @parsers = Parser.all(:order => 'display_name')

    respond_to do |format|
      if @paste
        format.html { render }
      else
        format.html { response_to_missing_id }
      end
    end
  end

  # POST /pastes
  # POST /pastes.xml
  def create
    @paste = Paste.new(params[:paste])
    @parsers = Parser.all(:order => 'display_name')

    respond_to do |format|
      if @paste.code.blank?
        format.html {
          render :action => "new"
        }
      else
        if @paste.save
          format.html { redirect_to(@paste) }
        else
          format.html { render :action => "new" }
        end
      end
    end
  end

  # PUT /pastes/1
  # PUT /pastes/1.xml
  def update
    @paste = Paste.find_by_id(params[:id])
    @parsers = Parser.all(:order => 'display_name')

    respond_to do |format|
      if @paste
        if params[:paste].keys.include?('code') && params[:paste]['code'] == ''
          format.html {
            render :action => "edit"
          }
        else
          if @paste.update_attributes(params[:paste])
            format.html { redirect_to(@paste) }
          else
            format.html { render :action => "edit" }
          end
        end
      else
        format.html { response_to_missing_id }
      end
    end
  end

  # DELETE /pastes/1
  # DELETE /pastes/1.xml
  def destroy
    @paste = Paste.find_by_id(params[:id])

    respond_to do |format|
      if @paste
        @paste.destroy
        format.html { redirect_to root_path }
      else
        format.html {
          response_to_missing_id
        }
      end
    end
  end

  private
  def response_to_missing_id
    flash[:notice] = "Whoops, it looks like that paste doesn't exist.  Perhaps you should create a new one."
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def legal; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodePaste</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html{ :xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", :lang => "end"}
  %head
    %meta{:http_equiv => 'content-type', :content => 'text/html;charset=UTF-8'}
    %title Code Paste
    = javascript_include_tag 'prototype', 'ZeroClipboard'
    = stylesheet_link_tag 'app'
    = stylesheet_link_tag 'syntax/blackboard.css'

  %body
    #header
      #header-nav
        = link_to 'New', root_path
        %span.spacer
        %span.spacer
        %span.spacer
        %span.spacer
        %span.spacer
        = link_to 'All', pastes_path
    #container
      - if flash[:notice]
        %p.flash-notice #{flash[:notice]}
      = yield
    .clear
    #footer
      #footer-links
        #footer-link-legal
          = link_to 'Legal', :controller => 'static', :action => 'legal'
        #footer-link-source
          = link_to 'Want to run your own version of this?', "http://github.com/thbishop/code-paste/tree/master"

app/views/pastes/_paste_form.haml
#content
  #code
    #new-code-block
      = form_for(@paste) do |f|
        = if @paste.errors.any?
          %ul
            - @paste.errors.full_messages.each do |msg|
              %li= msg
        #new-paste-box
          = f.text_area :code, :rows => 26, :cols => 60, :class => 'code-paste-text-area'
        #new-paste-options
          = f.collection_select(:parser_id, @parsers, :id, :display_name, { :include_blank => false } )
          %span.spacer
          %span.spacer
          %span.spacer
          %span.spacer
          = f.submit 'Paste'
      .clear

app/views/pastes/_pasted_details.html.haml
%table.paste-info{:cellspacing => '0', :cellpadding => '0'}
  %tr
    %td.stat-heading{:colspan => 2} Pasted
  %tr
    %td.paste-info-key as
    %td.stat 
      = " #{@paste.parser.display_name}" if @paste.parser
  %tr
    %td.paste-info-key on
    %td.stat 
      = " #{@paste.updated_at.to_datetime.strftime("%-1m/%-1d/%y")} "
  %tr
    %td.paste-info-key at
    %td.stat 
      = " #{@paste.updated_at.localtime.strftime("%I:%M %p (%Z)")}"

app/views/pastes/edit.html.haml
= render :partial => 'paste_form'
#right
  = render :partial => 'pasted_details'
  %br
  = link_to 'raw', paste_path(@paste, :format => :txt)
  %span.spacer
    |
  = link_to 'delete', @paste, :confirm => 'Are you sure?', :method => :delete
.clear

app/views/pastes/index.html.haml
#content
  #all-pastes
    #all-pastes-count
      %span.all-pastes-header All pastes
      %span.all-pastes-header-sub (#{@all_pastes_count} so far)
      #pagination-container.paste-pagination-summary
        = page_entries_info @pastes, :html => false
    - for paste in @pastes
      .paste-summary
        %p.paste-summary-header-action
          = link_to 'view', paste_path(paste), { :class => 'link-spacer' }
        %p.paste-summary-header-info
          = paste.parser.display_name + " (" + paste.number_of_lines.to_s + " lines)"
        .paste-summary-code
          - paste.number_of_lines < 10 ? text_rows = paste.number_of_lines : text_rows = 10
          = text_area_tag 'paste-code-summary', paste.code_summary(10), { :disabled => true, :rows => text_rows, :class => 'paste-code-summary-text-area' }
    #pagination-container.paste-pagination
      = will_paginate @pastes, :container => false, :previous_label => '<', :next_label => '>'
    .clear
#right
  %table{:width => '100%', :cellspacing => '0', :cellpadding => '0', :border => '0'}
    %tr
      %td.stat-heading{:colspan => '2'} Paste History
    %tr
      %td Past 24 Hours
      %td.lang-stat-count #{@day_count}
    %tr
      %td Past 7 Days
      %td.lang-stat-count #{@day_count}
    %tr
      %td This Month
      %td.lang-stat-count #{@this_month_count}
    %tr
      %td Last Month
      %td.lang-stat-count #{@last_month_count}
    %tr
      %td This Year
      %td.lang-stat-count #{@this_year}
  %br
  %br
  %table{:width => '100%', :cellspacing => '0', :cellpadding => '0', :border => '0'}
    %tr
      %td.stat-heading{:colspan => '2'} By Language (all time)
    - @lang_counts.sort_by{ |k,v| v}.reverse.each do |p_cnt|
      %tr
        %td #{p_cnt[0]}
        %td.lang-stat-count #{p_cnt[1]}
  %br
  %br
  %br
.clear

app/views/pastes/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodePaste</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pastes/new.html.haml
= render :partial => 'paste_form'
#right
  %span.right-heading Just paste your code in the box and select the language
  %br
.clear

app/views/pastes/show.html.haml
#content
  #code.blackboard
    #code-content
      %table
        %tr
          %td
            %pre{:id => 'source-numbers', :class => 'blackboard'}  <span class="Comment">#{@paste.line_numbers}</span>
          %td
            = find_and_preserve(raw @paste.highlighted_code)
#right
  = render :partial => 'pasted_details'
  %br
  #right-actions
    = link_to 'raw', paste_path(@paste, :format => :txt)
    %span.spacer
      |
    = link_to 'edit', edit_paste_path(@paste)
    %br
    %br
    %div#clip-copy-container
      = image_tag('clip_22_22.png', { :id => 'copy-img', :alt => 'copy to clip board', :size => '22x22' } )
    %span#clip-copy-text{:style => 'display: none'}
      copy code to clipboard
.clear

:preserve
  #{hidden_field(:paste, :code)}

:javascript
  ZeroClipboard.setMoviePath( '/ZeroClipboard.swf' );

  var clip = new ZeroClipboard.Client();
  clip.setHandCursor( true );
  clip.setCSSEffects( false );

  clip.setText( document.getElementById('paste_code').value );

  clip.addEventListener( 'mouseOver', function(client) {
    $('clip-copy-text').show();
  } );

  clip.addEventListener( 'mouseOut', function(client) {
    $('clip-copy-text').hide();
  } );

  clip.glue('copy-img', 'clip-copy-container');